server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/customersdb"
    username: root
    password: 0389618799@Cuc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "uPisGJb0hOHQJMxBjxsNPLkPY6HYlbMG9Vm/P6JKEDn6DeMQmy9bUYkEHGyiRjVF"
